/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package chessboard

import chessboard.enums.PieceType.{BR, BH, BB, BQ, BK, BP, WR, WH, WB, WQ, WK, WP}

import scala.util.{Failure, Success}

object Driver {
  def main(args: Array[String]): Unit = {
    val chessboard = new Chessboard
    println(chessboard)
    println("")

    List(
      (WP, (6, 4), (4, 4)),
      (BP, (1, 4), (3, 4)),
      (WH, (7, 6), (5, 5)),
      (BH, (0, 1), (2, 2)),
      (WH, (5, 5), (3, 4)),
      (BQ, (0, 3), (1, 4)),
      (WP, (6, 3), (4, 3)),
      (BQ, (1, 4), (3, 4)),
      (WP, (4, 3), (3, 4)),

      //invalid moves
      (WP, (4, 3), (3, 4)),
      (WP, (40, 3), (3, 4)),


    ).foreach(cmd => {
      chessboard.move(cmd._1, cmd._2, cmd._3) match {
        case Failure(exception) => println(exception.getMessage)
        case _ =>
      }
      println(chessboard)
      println("")
//      Thread.sleep(2000)
    })
  }
}
